# Generated by Django 5.1.7 on 2025-03-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_reservation_email_reservation_nombre_personne'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='mohamedahmim@icloud.com', max_length=254),
        ),
    ]
